import type { Metadata } from "next"; // Next.js'ten Metadata tipini içe aktarıyoruz
import { Inter } from "next/font/google"; // Google Fonts'tan Inter fontunu içe aktarıyoruz

const inter = Inter({ subsets: ["latin"] }); // Inter fontunu Latin karakter setiyle yapılandırıyoruz

export const metadata: Metadata = {
  title: "Create Next App", // Sayfa başlığını belirliyoruz
  description: "Generated by create next app", // Sayfa açıklamasını belirliyoruz
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {" "}
      {/* HTML dilini İngilizce olarak ayarlıyoruz */}
      <body className={inter.className}>{children}</body>{" "}
      {/* Inter fontunu uygulayarak sayfa içeriğini render ediyoruz */}
    </html>
  );
}
